services:
  backend:
    build: .
    command: uv run uvicorn app.main:app --reload --port=8000 --host=0.0.0.0
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    # environment:
    #   - NOTION_API_KEY=${NOTION_API_KEY}